steps:
  - name: node:14
    entrypoint: yarn
    args: ["install"]

  - name: node:14
    entrypoint: yarn
    args: ["build:prod"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app.prod.yaml"]

timeout: "1600s"
