export enum QUERY_KEYS {
  FETCH_MEMBER = "FETCH_MEMBER",
  FETCH_MEMBER_TODOS = "FETCH_MEMBER_TODOS",
  CREATE_PROGRESS = "CREATE_PROGRESS",
  CHECK_TRIGGER_REQUEST = "CHECK_TRIGGER_REQUEST",
  UPLOAD_MEMBER_AVATAR = "UPLOAD_MEMBER_AVATAR",
}

export enum QUERY_STATUS {
  IDLE = "idle",
  ERROR = "error",
  LOADING = "loading",
}
