export enum QUERY_KEYS {
  FETCH_MEMBER = "FETCH_MEMBER",
  FETCH_MEMBER_TODOS = "FETCH_MEMBER_TODOS",
  FETCH_CARE_TEAM_LIST = "FETCH_CARE_TEAM_LIST",
  FETCH_SCORE_PROGRESS_HISTORY = "FETCH_SCORE_PROGRESS_HISTORY",
  CREATE_PROGRESS = "CREATE_PROGRESS",
  CHECK_TRIGGER_REQUEST = "CHECK_TRIGGER_REQUEST",
  UPLOAD_MEMBER_AVATAR = "UPLOAD_MEMBER_AVATAR",
  UPDATE_PROFILE_FORM = "UPDATE_PROFILE_FORM",
  UPDATE_CHECKIN_FORM = "UPDATE_CHECKIN_FORM",
  UPDATE_INTAKE_FORM = "UPDATE_INTAKE_FORM",
  UPDATE_COORDINATION_FORM = "UPDATE_COORDINATION_FORM",
  UPLOAD_FILE = "UPLOAD_FILE",
  SUBMIT_FEEDBACK = "SUBMIT_FEEDBACK",
}

export enum QUERY_STATUS {
  IDLE = "idle",
  ERROR = "error",
  LOADING = "loading",
}
